# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_sessiontoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionToken',
            new_name='UserSessionToken',
        ),
    ]
