# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20170726_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='fullname',
            new_name='name',
        ),
    ]
