# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0004_auto_20170720_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='text',
            new_name='name',
        ),
    ]
