# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0006_auto_20170720_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
